name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm run lint
      - run: pip install -r requirements.txt
      - run: black --check .
      - run: pylint tests/*.py
      - run: pylint app/*.py
      - run: pylint app/blueprints/*.py
