name: Automated Flask testing
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  test:
    strategy:
      matrix:
        browser: [firefox, chromium]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
      - run: pip install pytest-playwright flask
      - run: python -m playwright install ${{ matrix.browser }}
      - run: cd app && flask run --port 8000 && cd .. &
      - run: pytest --durations=5 --browser ${{ matrix.browser }}
