name: Automated Flask testing
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install pytest-playwright
      - run: python -m playwright install
      - run: pip install flask
      - run: cd app && flask run --port 8000 && cd .. &
      - run: pytest --browser chromium --browser firefox
