name: Automated HTTP server testing
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python -m playwright install
      - run: python -m twisted web --port tcp:8000 --path www &
      - run: pytest --durations=5 --browser chromium --browser firefox
